export { createExtractorsPlugin, getExtractorId } from "./ExtractorsPlugin"
export { styledIdPlugin } from "./styledIdPlugin"
export { PluginContextCollector } from "./PluginContextCollector"

export type { StyleExtractor, DerivedExtractorBinding, FileInfo } from "./types"
export { StyleGenerator } from "./types"
export type { ImportSpecStageOut, ExtractorLookup, FileData } from "./stages/ImportSpecStage"
export { makeImportSpecStage, IMPORT_SPEC_STAGE } from "./stages/ImportSpecStage"
export type { DerivedExtractorStageOut } from "./stages/DerivedExtractorStage"
export { makeDerivedExtractorStage, DERIVED_EXTRACTOR_STAGE } from "./stages/DerivedExtractorStage"
export type { StyleExprStageOut } from "./stages/StyleExprStage"
export { makeStyleExprStage, STYLE_EXPR_STAGE } from "./stages/StyleExprStage"
export type { BindingStageOut } from "./stages/BindingStage"
export { makeBindingStage, BINDING_STAGE } from "./stages/BindingStage"
export type { CrossFileDerivedStageOut, CrossFileExtra, CrossFileResult } from "./stages/CrossFileDerivedStage"
export { makeCrossFileDerivedStage, CROSS_FILE_DERIVED_STAGE } from "./stages/CrossFileDerivedStage"
export { extractRelevantSymbols } from "./extractRelevantSymbols"

// Re-export commonly needed builder types for plugin authors
export type { AstPostProcessor, EmitHook, BuilderOptions, RootEntry, StageDefinition } from "@mochi-css/builder"
