export { createExtractorsPlugin, getExtractorId } from "./ExtractorsPlugin"
export { styledIdPlugin } from "./styledIdPlugin"
export { PluginContextCollector } from "./PluginContextCollector"

export type { StyleExtractor, DerivedExtractorBinding, FileInfo } from "./types"
export { StyleGenerator } from "./types"
export type { ImportSpecStageOut, ExtractorLookup } from "./stages/ImportSpecStage"
export { importStageDef } from "./stages/ImportSpecStage"
export type { DerivedExtractorStageOut } from "./stages/DerivedExtractorStage"
export { derivedStageDef } from "./stages/DerivedExtractorStage"
export type { StyleExprStageOut } from "./stages/StyleExprStage"
export { styleExprStageDef } from "./stages/StyleExprStage"
export type { BindingStageOut } from "./stages/BindingStage"
export { bindingStageDef } from "./stages/BindingStage"
export type { CrossFileDerivedStageOut, CrossFileExtra, CrossFileResult } from "./stages/CrossFileDerivedStage"
export { crossFileDerivedStageDef } from "./stages/CrossFileDerivedStage"
export type { ExportsStageOut, ExportsStageResult, ReexportEntry } from "./stages/Exports"
export { exportsStage } from "./stages/Exports"
export { extractRelevantSymbols } from "./extractRelevantSymbols"
export { getOrInsert, isLocalImport } from "./utils"
export { propagateUsagesFromRef, propagateUsagesFromExpr } from "./propagation"
export type { ReexportResolver } from "./propagation"

// Re-export commonly needed builder types for plugin authors
export type { AstPostProcessor, EmitHook, BuilderOptions, RootEntry, StageDefinition } from "@mochi-css/builder"
